### ISSUE TITLE
Question: Plex Requests for TV Handling

### ISSUE THREAD

**Issue by ekk88d** [antifuchs/sonarr-plex-cleaner#3]
Hi, I'd like to clarify how _sonarr-plex-cleaner_ handles Plex requests approved for TV episodes, specifically episodes requested/approved that are outside the `retain_policy`.

- If the `retain_policy` is specified as `14d`, what does _SPC_ do when a user requests 2 seasons at a time?

> Ex: The requested series is currently airing S02E04 and Season 1 had 10 episodes.
Season 1 is past the `retain_policy` setting, along with E01-E02 of Season 2.

If we see the old TV shows requested/downloaded, we'd either give the series a manual `retain_tag` or users who download old TV shows have a week (max) to watch their old requested shows (S01E01-S02E02). If not manually-retained, the old shows are marked for deletion next job run. Is that correct?

Lastly, a 2-parter:

- When movies or episodes are deleted by _SBC_, are they also unmonitored? I didn't notice that piece specified on the existing docs. If episodes are able to get deleted singly, is a Season unmonitored when all of its episodes are deleted by a _SPC_ run?

Thanks for developing this utility. It's going to come in handy for me.

**Comment by antifuchs** [comment]
Thanks for the in-depth questions! I will try to answer as best I can!

1. the `retain_duration` (I assume you mean that when you write `retain_policy`?) applies only to seasons that are eligible for deletion: That is, seasons that are not currently airing and have had all their episodes watched (or marked as watched) by the given Plex user. Overall, SPC only operates on entire seasons at a time - either the entire season is eligible for deletion, or not. That also affects the `retain_duration` in a somewhat implicit way: The season's most recent episode must have been aired at least that long ago, _in addition_ to the above criteria, so that the season is eligible for deletion.

2. Seasons that get deleted are marked as un-monitored, yep: [Here](https://github.com/antifuchs/sonarr-plex-cleaner/blob/851a2f617f2a737b9a1edf1fa21c61c4209a4f9c/src/commands/tv.rs#L194-L195) is where that happens. That is only done when the episode files get deleted (using the `-f` cli switch).

I notice that you refer to movies: SPC currently doesn't work on movies at all; I have been tempted to extend it to do that, but I love keeping movies around too much, so that functionality is not there right now (:

Hope that helps! I'll close this issue, but if there's anything else unclear, feel free to re-open.
